### ISSUE TITLE
这个视频补帧插件有兴趣汉化吗？

### ISSUE THREAD

**Issue by wibur0620** [AIGODLIKE/AIGODLIKE-ComfyUI-Translation#188]
https://github.com/Fannovel16/ComfyUI-Frame-Interpolation

**Comment by Nestorchik** [comment]
There is no information on how to contact the author (((
I tested the Russian language, everything is fine. But I would like the English version to be posted in full somewhere, I would copy it to the Russian folder "ru-RU", and start the translation. Sign me up as the person responsible for the translation into Russian. I am a programmer, my repository is in my profile. He edited the Russian language on the comflowyspace project. Access can be done via "GIT - Pull".

![222](https://github.com/AIGODLIKE/AIGODLIKE-ComfyUI-Translation/assets/74113797/014d3cba-bd7f-4915-9155-a47101bfe65c)

**Comment by wibur0620** [comment]
https://github.com/Extraltodeus/ComfyUI-AutomaticCFG?tab=readme-ov-file
这个小插件有兴趣翻译吗？

**Comment by Nestorchik** [comment]
我有兴趣翻译一切ComfyUI

我需要GIT上的英语语言文件。 我会为自己做一个分支，随着翻译的进展，我会提出合并我和主分支的请求。 我只对俄语感兴趣。

**Comment by Nestorchik** [comment]
我试过了，一切都很好，我甚至不必更改文件的编码。 我曾经在"Comflowy"中编辑俄语，我只是为自己创建了一个分支，在git上翻译了提交和PR。

**Comment by Nestorchik** [comment]
https://t.me/stable_cascade_rus
https://t.me/srigert

**Comment by wibur0620** [comment]
> 我试过了，一切都很好，我甚至不必更改文件的编码。 我曾经在"Comflowy"中编辑俄语，我只是为自己创建了一个分支，在git上翻译了提交和PR。

Hello! It's great to see more people joining the team for translating plugins. Firstly, I'm not the author of this repository; I'm here to request translations for plugins as well. But rest assured, when the author of this repository sees your message, they will get in touch with you. The author is a very nice person with a strong sense of responsibility. It's possible that lately, their company has been keeping them very busy, so they might be a bit overwhelmed and unable to attend to things here promptly.

**Comment by Nestorchik** [comment]
OK. Let's wait...

**Comment by Yorha4D** [comment]
@Nestorchik Hi, friend, just submit a pr or call me anytime

**Comment by DorotaLuna** [comment]
Oh, I see...

Hi, @Nestorchik, I'm not exactly sure what the "the English version to be posted in full" meaning. 
If you need full English nodes content, you can use zh-CN translation, it contains both original English content and Chinese, just directyly replace Chinese translation with your translation. Then add ru-RU language option at `LocaleMap.json`

ComfyUI-Translation
├─zh-CN <- change this to ru-RU
│ ├─Nodes
│ │ ├─internal.json <- comfyui internal nodes
│ │ ├─extension.json <- extension nodes
│ ├─menu.json <- menu, node options, search options
│ └─NodeCategory.json <- right click category

**Comment by Nestorchik** [comment]
OK

**Comment by DorotaLuna** [comment]
> https://github.com/Fannovel16/ComfyUI-Frame-Interpolation

> https://github.com/Extraltodeus/ComfyUI-AutomaticCFG?tab=readme-ov-file 这个小插件有兴趣翻译吗？


更了，github的resolve conflict太难用所以没用pr

**Comment by Nestorchik** [comment]
I'll take care of "ComfyUI" for now

**Comment by wibur0620** [comment]
> > https://github.com/Fannovel16/ComfyUI-Frame-Interpolation
> 
> > https://github.com/Extraltodeus/ComfyUI-AutomaticCFG?tab=readme-ov-file 这个小插件有兴趣翻译吗？
> 
> 更了，github的resolve conflict太难用所以没用pr
谢谢！
resolve conflict确实有点难用，之前在群里，就听到有人在说这个。辛苦了哈，同时我在这里也欢迎以下上面这位翻译俄语的兄弟加入

**Comment by wibur0620** [comment]
我在本地改了下这个
![{32F91370-1A76-468a-92DE-DD8A39FC6DE6}](https://github.com/AIGODLIKE/AIGODLIKE-ComfyUI-Translation/assets/131615326/953aa2ed-94a8-49c5-9176-5f8c1ff88921)
现在显示图标了
![{08C9B0CC-737A-489e-87AC-677C82FD2143}](https://github.com/AIGODLIKE/AIGODLIKE-ComfyUI-Translation/assets/131615326/792759e9-7fe6-40c5-bb1a-0d561add2adc)
你看，有空的话改一下吧，有这个图标好看些

**Comment by Nestorchik** [comment]
是什么阻止您返回并删除不无聊的内容？ ）））

  
>Вторник, 2 апреля 2024, 13:04 +03:00 от DorotaL ***@***.***>:
> 
> 
>我在本地改了下这个  现在显示图标了  你看，有空的话改一下吧，有这个图标好看些
#194

**Comment by DorotaLuna** [comment]
> 是什么阻止您返回并删除不无聊的内容？ ）））  

I think you can use english or russian directly, this chinese comment is really hard to understand.
If I understand you correctly, which is 'What makes you back here and did not delete the boring request comment'.
That is because I think his opinion is reasonable, since I translated other "content with emoji" with emoji not just remove all emojis, this addon should also save the emoji, though I think remove all emojis are better but that might cause confuse to those who is more familiar english name than chinese.

**Comment by Nestorchik** [comment]
Ок. Без проблемм.
 
Я удаляю в своем варианте файлов смайлики и в английской версии, и в русской.
Просто я — программист, и в прошлом имел большое количество ошибок при конвертации из одних кодовых страниц в другую, поэтому взял за правило:

- «Текст должен содержать буквы, вхдящие в диапазон адресов 128-254»
- «Если в тексте находятся еще символы, не относящиеся к буквам, то как они будут выглядеть в другой кодвой странице — непредсказуемо»
  
>Вторник, 2 апреля 2024, 14:02 +03:, 00 от DorotaL ***@***.***>:
> 
> 
>是什么阻止您返回并删除不无聊的内容？ ）））  
I think you can use english or russian directly, this chinese comment is really hard to understand.
If I understand you correctly, which is 'What makes you back here and did not delete the boring request comment'.
That is because I think his opinion is reasonable, since I translated other "content with emoji" with emoji not just remove all emojis, this addon should also save the emoji, though I think remove all emojis are better but that might cause confuse to those who is more familiar english name than chinese.
